# ===========================================
# RuboCop Configuration Template
# Usage: Copy to project root
# ===========================================

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'tmp/**/*'

# ===========================================
# Layout
# ===========================================

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '^\s*#'  # Comments

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

# ===========================================
# Metrics
# ===========================================

Metrics/MethodLength:
  Max: 20
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/ClassLength:
  Max: 150
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
    - 'Rakefile'
    - 'config/routes.rb'

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

# ===========================================
# Style
# ===========================================

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

# ===========================================
# Naming
# ===========================================

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_

Naming/MethodParameterName:
  MinNameLength: 2
  AllowedNames:
    - id
    - to
    - by
    - db
    - io

# ===========================================
# RSpec
# ===========================================

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'
    - 'spec/features/**/*'
    - 'spec/system/**/*'

# ===========================================
# Performance
# ===========================================

Performance/Caller:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

Performance/Sum:
  Enabled: true

Performance/MapCompact:
  Enabled: true
